# Generated by Django 5.2.6 on 2025-09-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useractive_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractive',
            name='is_active',
        ),
    ]
