# Generated by Django 5.2.6 on 2025-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useractive_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractive',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
